### ISSUE TITLE
Allow sonar task to accept projectKey and projectName via param

### ISSUE THREAD

**Issue by nareshgnT** [homedepot/flow#53]
Currently flow sonar takes `projectKey` and `projectName` from `buildConfig.json` and allows `projectVersion` can be passed as param. We used `projectVersion` parameter for feature branch scanning. But recent changes to Sonar does not support `projectVersion` any more . So we are not able to scan for feature branch. We can still use flow if it allows to override `projectKey` and `projectName` via param. So when feature branch is scanning we will set key and name to append feature branch with repo name

**Comment by WRMilling** [comment]
@nareshgnT I am assuming this is fixed by #54 and am closing this issue. Let me know if there are any problems.
